name: Automated Compliance Audit
on:
  workflow_run:
    workflows: ["Deploy Mock Infra"]
    types: [completed] # after deployedment audit will start

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    # olny work when deployement is successfull
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Boto3
        run: pip install boto3

      - name: Run SOC2 Auditor Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
        run: python scripts/collect_evidence.py

      - name: Upload Audit Evidence
        uses: actions/upload-artifact@v4
        with:
          name: soc2-compliance-report
          path: evidence/compliance_report.json # this is our fianl proof