name: SOC2 Compliance Audit

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM
  workflow_dispatch:     # Allows you to run it manually for the demo
  push:
    branches: [ main ]   # Runs every time you update your code

jobs:
  compliance-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ðŸ”‘ This step allows GitHub to log into your AWS account securely
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Match this to your Terraform region

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install boto3

      - name: Collect SOC2 Evidence
        run: python scripts/collect_evidence.py

      # ðŸ“¦ This saves the JSON report so you can download it for the auditor
      - name: Upload Evidence Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soc2-evidence-report
          path: evidence/